# .github/cliff.toml

[changelog]
# Убран верхний заголовок "What's Changed?"
header = ""

# Форматирование: Чистые раздельные ветки для PR и прямых коммитов
body = """
{% for group, commits in commits | group_by(attribute="group") %}
## {{ group }}
{% for commit in commits %}
{% if commit.remote.pr_number %}\
- {{ commit.message | split(pat="\n") | first | trim | upper_first }} (#{{ commit.remote.pr_number }}) {% if commit.remote.username %}@{{ commit.remote.username }}{% elif commit.author.name %}@{{ commit.author.name }}{% endif %}
{% else %}\
- {{ commit.message | split(pat="\n") | first | trim | upper_first }} ([{{ commit.id | truncate(length=7, end="")) }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}) {% if commit.remote.username %}@{{ commit.remote.username }}{% elif commit.author.name %}@{{ commit.author.name }}{% endif %}
{% endif %}\
{% endfor %}
{% endfor %}
{% if previous.version and version %}
---

**Full Changelog**: [`{{ previous.version }}...{{ version }}`](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }})
{% endif %}
"""
footer = ""
trim = true

# Секция для корректного рассчета следующей версии
[bump]
initial_tag = "v0.1.0"

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false

commit_parsers = [
  # Пропускаем служебные коммиты
  { message = "^chore\\(release\\)", skip = true },
  { message = ".*[Sk|sk]ip [Re|re]lease.*", skip = true },

  # 💥 Breaking Changes
  { body = ".*BREAKING CHANGE.*", group = "💥 Breaking Changes" },
  { message = "^.*!: ", group = "💥 Breaking Changes" },

  # ⭐ Features
  { message = "^feat", group = "⭐ Features" },

  # 🐞 Bug Fixes
  { message = "^fix", group = "🐞 Bug Fixes" },

  # 🛠 Improvements
  { message = "^perf", group = "🛠 Improvements" },
  { message = "^refactor", group = "🛠 Improvements" },
  { message = "^style", group = "🛠 Improvements" },
  { message = "^chore", group = "🛠 Improvements" },

  # 📖 Documentation
  { message = "^docs", group = "📖 Documentation" },

  # 🌍 Localization
  { message = "^i18n", group = "🌍 Localization" },
  { message = "^loc", group = "🌍 Localization" },

  # 🌀 External Changes
  { message = "^deps", group = "🌀 External Changes" },
  { message = "^build\\(deps\\)", group = "🌀 External Changes" },
  { message = "^chore\\(deps\\)", group = "🌀 External Changes" },
  { message = "^plugin", group = "🌀 External Changes" },

  # Все остальные коммиты и PR попадают сюда
  { message = ".*", group = "🛠 Improvements" },
]

protect_breaking_commits = false
filter_commits = false
tag_pattern = "v?[0-9].*"
skip_tags = ""
ignore_tags = ""
sort_commits = "oldest"