name: Release Drafter (git-cliff)

on:
  push:
    branches:
      - main
      - lts

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Требуется для корректного чтения истории git и тегов

      - name: Generate Changelog with git-cliff
        id: git-cliff
        uses: orhun/git-cliff-action@v4
        with:
          config: cliff.toml
          args: --unreleased --bump
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create or Update GitHub Draft Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: ${{ steps.git-cliff.outputs.version }}
          name: ${{ steps.git-cliff.outputs.version }}
          body: ${{ steps.git-cliff.outputs.content }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}